-- Account users let one Supabase login act as a shared account
-- while still tracking which person performed each stock movement.

CREATE TABLE IF NOT EXISTS public.account_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id uuid REFERENCES public.users (id) ON DELETE CASCADE NOT NULL,
    name text NOT NULL,
    role text,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.account_users ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage own account users" ON public.account_users;
CREATE POLICY "Users can manage own account users"
    ON public.account_users FOR ALL
    TO authenticated
    USING (account_id = auth.uid())
    WITH CHECK (account_id = auth.uid());

ALTER TABLE public.stock_movements
    ADD COLUMN IF NOT EXISTS account_user_id bigint
    REFERENCES public.account_users (id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS account_users_account_name_idx
    ON public.account_users (account_id, name);

CREATE INDEX IF NOT EXISTS stock_movements_account_user_idx
    ON public.stock_movements (account_user_id);

DROP POLICY IF EXISTS "Users can manage own stock movements" ON public.stock_movements;
CREATE POLICY "Users can manage own stock movements"
    ON public.stock_movements FOR ALL
    TO authenticated
    USING (
        user_id = auth.uid()
        AND EXISTS (
            SELECT 1
            FROM public.products
            WHERE products.id = stock_movements.product_id
                AND products.user_id = auth.uid()
        )
        AND (
            account_user_id IS NULL
            OR EXISTS (
                SELECT 1
                FROM public.account_users
                WHERE account_users.id = stock_movements.account_user_id
                    AND account_users.account_id = auth.uid()
            )
        )
    )
    WITH CHECK (
        user_id = auth.uid()
        AND EXISTS (
            SELECT 1
            FROM public.products
            WHERE products.id = stock_movements.product_id
                AND products.user_id = auth.uid()
        )
        AND (
            account_user_id IS NULL
            OR EXISTS (
                SELECT 1
                FROM public.account_users
                WHERE account_users.id = stock_movements.account_user_id
                    AND account_users.account_id = auth.uid()
            )
        )
    );
