/* * ======================================================================================
 * INVENTORY MANAGEMENT SYSTEM SCHEMA
 * ======================================================================================
 * This schema handles multi-tenant inventory management.
 * - Users: The business owners using the app.
 * - Customers/Suppliers: Entities related to a specific User.
 * - Products: Inventory items owned by the User.
 * - Orders: Inbound transactions (Buying stock from Suppliers).
 * - Sales: Outbound transactions (Selling stock to Customers).
 * ======================================================================================
 */
-- 1. USERS
-- Stores the application users (Business Owners).
-- Linked directly to Supabase Authentication.
CREATE TABLE
    public.users (
        id uuid REFERENCES auth.users NOT NULL PRIMARY KEY, -- Links to Supabase Auth ID
        email text,
        name text, -- Display name of the business owner
        profile_picture text, -- URL to the image storage
        created_at timestamp
        with
            time zone DEFAULT now (),
            updated_at timestamp
        with
            time zone DEFAULT now ()
    );

-- --------------------------------------------------------------------------------------
-- 2. CUSTOMERS
-- The clients/buyers of the Business Owner.
CREATE TABLE
    public.customers (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name text NOT NULL,
        contact_number text,
        address text, -- Shipping or billing address
        user_id uuid REFERENCES public.users (id), -- The business owner who owns this customer data
        created_at timestamp
        with
            time zone DEFAULT now ()
    );

-- --------------------------------------------------------------------------------------
-- 3. SUPPLIERS
-- The vendors/distributors from whom the Business Owner buys products.
CREATE TABLE
    public.suppliers (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        supplier_name text NOT NULL,
        contact_number text,
        address text,
        purchase_link text, -- E.g., Link to Tokopedia/Shopee/Website
        user_id uuid REFERENCES public.users (id),
        created_at timestamp
        with
            time zone DEFAULT now ()
    );

-- --------------------------------------------------------------------------------------
-- 4. PRODUCTS
-- The main inventory catalog.
CREATE TABLE
    public.products (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product_name text NOT NULL,
        product_type text, -- Legacy mirror of product_category for older app code
        product_category text, -- The single material category used by the UI
        amount_stock integer DEFAULT 0 NOT NULL, -- Current quantity on hand
        buy_price numeric(15, 2) DEFAULT 0.00 NOT NULL, -- Legacy optional price field, not used by the stock-in/out UI
        sell_price numeric(15, 2) DEFAULT 0.00 NOT NULL, -- Legacy optional price field, not used by the stock-in/out UI
        product_image text, -- URL to image storage
        supplier_id bigint REFERENCES public.suppliers (id) ON DELETE SET NULL, -- Default supplier for this item
        user_id uuid REFERENCES public.users (id),
        created_at timestamp
        with
            time zone DEFAULT now ()
    );

-- --------------------------------------------------------------------------------------
-- 4.1 STOCK MOVEMENTS
-- Records every manual stock-in and stock-out action with actor and notes.
CREATE TABLE
    public.stock_movements (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product_id bigint REFERENCES public.products (id) ON DELETE CASCADE NOT NULL,
        user_id uuid REFERENCES public.users (id) NOT NULL,
        movement_type text NOT NULL CHECK (movement_type IN ('in', 'out')),
        quantity integer NOT NULL CHECK (quantity > 0),
        note text,
        created_at timestamp
        with
            time zone DEFAULT now ()
    );

CREATE INDEX IF NOT EXISTS stock_movements_product_created_idx
    ON public.stock_movements (product_id, created_at DESC);

-- --------------------------------------------------------------------------------------
-- 5. ORDER SEQUENCES 
-- Helper table to generate readable Purchase Order codes (e.g., PO-202310-001).
-- It tracks the last number used for a specific month/year key.
CREATE TABLE
    public.order_sequences (
        date_key text NOT NULL PRIMARY KEY, -- Format: YYYYMM (e.g., '202310')
        last_number bigint DEFAULT 0 -- Increments for every new order in that month
    );

-- 6. INVOICE SEQUENCES 
-- Helper table to generate readable Invoice codes (e.g., INV-202310-001).
CREATE TABLE
    public.invoice_sequences (
        date_key text NOT NULL PRIMARY KEY, -- Format: YYYYMM
        last_number bigint DEFAULT 0
    );

-- --------------------------------------------------------------------------------------
-- 7. ORDERS (PURCHASE ORDERS)
-- Represents Inbound Transactions (Restocking items from Suppliers).
CREATE TABLE
    public.orders (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        po_code text UNIQUE, -- Human-readable code (e.g., PO-202310-001)
        status text NOT NULL DEFAULT 'Pending', -- Enum: 'Pending', 'Shipped', 'Completed', 'Cancelled'
        total_cost numeric(15, 2) DEFAULT 0.00, -- Total value of the purchase
        expected_delivery_date timestamp without time zone,
        supplier_id bigint REFERENCES public.suppliers (id) ON DELETE SET NULL,
        user_id uuid REFERENCES public.users (id),
        created_at timestamp
        with
            time zone DEFAULT now ()
    );

-- 8. ORDER ITEMS
-- The specific products and quantities within a Purchase Order.
CREATE TABLE
    public.order_items (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id bigint REFERENCES public.orders (id) ON DELETE CASCADE NOT NULL, -- If Order is deleted, items are deleted
        product_id bigint REFERENCES public.products (id) ON DELETE RESTRICT NOT NULL, -- Cannot delete Product if it exists in an order
        quantity integer NOT NULL, -- Number of items ordered
        cost_per_item numeric(15, 2) NOT NULL, -- Historical cost at the time of purchase
        created_at timestamp
        with
            time zone DEFAULT now ()
    );

-- --------------------------------------------------------------------------------------
-- 9. SALES (INVOICES)
-- Represents Outbound Transactions (Selling items to Customers).
CREATE TABLE
    public.sales (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        invoice_code text UNIQUE, -- Human-readable code (e.g., INV-202310-001)
        sale_date timestamp
        with
            time zone DEFAULT now (),
            total_amount numeric(15, 2) DEFAULT 0.00, -- Total revenue from this sale
            payment_method text, -- E.g., 'Cash', 'Transfer', 'QRIS'
            payment_status text DEFAULT 'Paid', -- Enum: 'Paid', 'Unpaid', 'Partial'
            notes text, -- Optional notes for the invoice
            customer_id bigint REFERENCES public.customers (id) ON DELETE SET NULL,
            user_id uuid REFERENCES public.users (id) NOT NULL
    );

-- 10. SALES ITEMS
-- The specific products and quantities within a Sale.
CREATE TABLE
    public.sales_items (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sales_id bigint REFERENCES public.sales (id) ON DELETE CASCADE NOT NULL,
        product_id bigint REFERENCES public.products (id) ON DELETE RESTRICT NOT NULL,
        quantity integer NOT NULL, -- Number of items sold
        price_at_sale numeric(15, 2) NOT NULL, -- Selling price at that moment (Revenue)
        cost_at_sale numeric(15, 2) DEFAULT 0, -- Buy price at that moment (for Profit/Loss calculation)
        created_at timestamp
        with
            time zone DEFAULT now ()
    );

-- --------------------------------------------------------------------------------------
-- 11. ROW LEVEL SECURITY
-- Allows each authenticated user to manage only their own warehouse data.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own profile" ON public.users;
CREATE POLICY "Users can read own profile"
    ON public.users FOR SELECT
    TO authenticated
    USING (id = auth.uid());

DROP POLICY IF EXISTS "Users can insert own profile" ON public.users;
CREATE POLICY "Users can insert own profile"
    ON public.users FOR INSERT
    TO authenticated
    WITH CHECK (id = auth.uid());

DROP POLICY IF EXISTS "Users can update own profile" ON public.users;
CREATE POLICY "Users can update own profile"
    ON public.users FOR UPDATE
    TO authenticated
    USING (id = auth.uid())
    WITH CHECK (id = auth.uid());

INSERT INTO public.users (id, email, name)
SELECT
    auth.users.id,
    auth.users.email,
    COALESCE(
        auth.users.raw_user_meta_data ->> 'display_name',
        auth.users.raw_user_meta_data ->> 'name',
        split_part(auth.users.email, '@', 1),
        'User'
    )
FROM auth.users
ON CONFLICT (id) DO NOTHING;

CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    INSERT INTO public.users (id, email, name)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(
            NEW.raw_user_meta_data ->> 'display_name',
            NEW.raw_user_meta_data ->> 'name',
            split_part(NEW.email, '@', 1),
            'User'
        )
    )
    ON CONFLICT (id) DO NOTHING;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();

DROP POLICY IF EXISTS "Users can manage own customers" ON public.customers;
CREATE POLICY "Users can manage own customers"
    ON public.customers FOR ALL
    TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can manage own suppliers" ON public.suppliers;
CREATE POLICY "Users can manage own suppliers"
    ON public.suppliers FOR ALL
    TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can manage own products" ON public.products;
CREATE POLICY "Users can manage own products"
    ON public.products FOR ALL
    TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can manage own stock movements" ON public.stock_movements;
CREATE POLICY "Users can manage own stock movements"
    ON public.stock_movements FOR ALL
    TO authenticated
    USING (
        user_id = auth.uid()
        AND EXISTS (
            SELECT 1
            FROM public.products
            WHERE products.id = stock_movements.product_id
                AND products.user_id = auth.uid()
        )
    )
    WITH CHECK (
        user_id = auth.uid()
        AND EXISTS (
            SELECT 1
            FROM public.products
            WHERE products.id = stock_movements.product_id
                AND products.user_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Users can manage own orders" ON public.orders;
CREATE POLICY "Users can manage own orders"
    ON public.orders FOR ALL
    TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can manage own order items" ON public.order_items;
CREATE POLICY "Users can manage own order items"
    ON public.order_items FOR ALL
    TO authenticated
    USING (
        EXISTS (
            SELECT 1
            FROM public.orders
            WHERE orders.id = order_items.order_id
                AND orders.user_id = auth.uid()
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1
            FROM public.orders
            WHERE orders.id = order_items.order_id
                AND orders.user_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Users can manage own sales" ON public.sales;
CREATE POLICY "Users can manage own sales"
    ON public.sales FOR ALL
    TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can manage own sales items" ON public.sales_items;
CREATE POLICY "Users can manage own sales items"
    ON public.sales_items FOR ALL
    TO authenticated
    USING (
        EXISTS (
            SELECT 1
            FROM public.sales
            WHERE sales.id = sales_items.sales_id
                AND sales.user_id = auth.uid()
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1
            FROM public.sales
            WHERE sales.id = sales_items.sales_id
                AND sales.user_id = auth.uid()
        )
    );
