-- Run this in Supabase SQL Editor to enable stock movement history.
-- It is safe to run more than once.

CREATE TABLE IF NOT EXISTS public.stock_movements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint REFERENCES public.products (id) ON DELETE CASCADE NOT NULL,
    user_id uuid REFERENCES public.users (id) NOT NULL,
    movement_type text NOT NULL CHECK (movement_type IN ('in', 'out')),
    quantity integer NOT NULL CHECK (quantity > 0),
    note text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE INDEX IF NOT EXISTS stock_movements_product_created_idx
    ON public.stock_movements (product_id, created_at DESC);

ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage own stock movements"
    ON public.stock_movements;

CREATE POLICY "Users can manage own stock movements"
    ON public.stock_movements FOR ALL
    TO authenticated
    USING (
        user_id = auth.uid()
        AND EXISTS (
            SELECT 1
            FROM public.products
            WHERE products.id = stock_movements.product_id
                AND products.user_id = auth.uid()
        )
    )
    WITH CHECK (
        user_id = auth.uid()
        AND EXISTS (
            SELECT 1
            FROM public.products
            WHERE products.id = stock_movements.product_id
                AND products.user_id = auth.uid()
        )
    );

-- Optional backfill: creates one starting stock-in history row for existing products.
INSERT INTO public.stock_movements (
    product_id,
    user_id,
    movement_type,
    quantity,
    note,
    created_at
)
SELECT
    products.id,
    products.user_id,
    'in',
    products.amount_stock,
    'ยอดยกมาก่อนเริ่มบันทึกประวัติ',
    products.created_at
FROM public.products
WHERE products.amount_stock > 0
    AND products.user_id IS NOT NULL
    AND NOT EXISTS (
        SELECT 1
        FROM public.stock_movements
        WHERE stock_movements.product_id = products.id
    );
